# Generated by Django 3.1.1 on 2020-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='next_step',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
