# Generated by Django 3.1.1 on 2020-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsapp', '0002_auto_20200923_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='process_start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
